import { Colors, Font_Size, Fonts } from "@/constants/theme";
import { Platform, StyleSheet } from "react-native";

const H = 24;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.WHITE,
  },
  header: {
    backgroundColor: Colors.RED_2,
    paddingHorizontal: H,
    paddingBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontFamily: Fonts.serif,
    fontSize: Font_Size.LG,
    color: Colors.WHITE,
    fontWeight: Platform.OS === "ios" ? "600" : "bold",
  },
  deleteText: {
    color: Colors.WHITE,
    fontSize: Font_Size.SM,
    fontWeight: "600",
    minWidth: 56,
    textAlign: "right",
  },
  scroll: {
    flex: 1,
    flexGrow: 1,
  },
  scrollContent: {
    paddingHorizontal: H,
    paddingTop: 24,
    paddingBottom: 32,
  },
  photoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 28,
    gap: 16,
  },
  photoCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: Colors.SHAPE,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: Colors.GRAY_1,
  },
  photoPreview: {
    width: "100%",
    height: "100%",
  },
  photoPlaceholder: {
    fontSize: Font_Size.SM,
    color: Colors.SECONDARY_500,
    textAlign: "center",
    paddingHorizontal: 8,
  },
  loadBtn: {
    backgroundColor: Colors.RED_2,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
  },
  loadBtnText: {
    color: Colors.WHITE,
    fontWeight: "700",
    fontSize: Font_Size.SM,
  },
  label: {
    fontSize: Font_Size.SM,
    color: Colors.SECONDARY_900,
    fontWeight: "600",
    marginBottom: 8,
  },
  labelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  hint: {
    fontSize: Font_Size.XS,
    color: Colors.SECONDARY_500,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.SHAPE,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "ios" ? 14 : 12,
    fontSize: Font_Size.MD,
    color: Colors.SECONDARY_900,
    backgroundColor: Colors.WHITE,
    marginBottom: 20,
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: "top",
  },
  sizeRow: {
    flexDirection: "row",
    alignItems: "stretch",
    borderWidth: 1,
    borderColor: Colors.SHAPE,
    borderRadius: 10,
    marginBottom: 12,
    overflow: "hidden",
    backgroundColor: Colors.WHITE,
  },
  sizeLetter: {
    width: 56,
    borderRightWidth: 1,
    borderRightColor: Colors.SHAPE,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  sizeLetterText: {
    fontSize: Font_Size.LG,
    fontWeight: "700",
    color: Colors.SECONDARY_900,
  },
  sizePriceInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === "ios" ? 12 : 10,
    fontSize: Font_Size.MD,
    color: Colors.SECONDARY_900,
  },
  sectionTitle: {
    fontSize: Font_Size.MD,
    fontWeight: "700",
    color: Colors.SECONDARY_900,
    marginBottom: 12,
    marginTop: 4,
  },
  submitBtn: {
    marginTop: 24,
    backgroundColor: Colors.GREEN_2,
    borderRadius: 999,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtnDisabled: {
    opacity: 0.65,
  },
  submitBtnText: {
    color: Colors.WHITE,
    fontSize: Font_Size.MD,
    fontWeight: "700",
  },
  errorText: {
    color: Colors.RED_1,
    fontSize: Font_Size.SM,
    marginTop: -12,
    marginBottom: 12,
  },
  formError: {
    color: Colors.RED_1,
    fontSize: Font_Size.SM,
    marginBottom: 12,
    textAlign: "center",
  },
});
